// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type NewUser struct {
	Name        string `json:"Name"`
	Email       string `json:"Email"`
	Password    string `json:"Password"`
	PhoneNumber int    `json:"Phone_Number"`
}

type User struct {
	Name        string `json:"Name"`
	Email       string `json:"Email"`
	Password    string `json:"Password"`
	PhoneNumber int    `json:"Phone_Number"`
}

type GetUser struct {
	Email string `json:"Email"`
}
