// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type Buses struct {
	BusName   string `json:"Bus_Name"`
	BusNumber string `json:"Bus_Number"`
	TotalSeat int    `json:"Total_seat"`
}

type NewBus struct {
	BusName   string `json:"Bus_Name"`
	BusNumber string `json:"Bus_Number"`
	TotalSeat int    `json:"Total_seat"`
}

type NewUser struct {
	Name        string `json:"Name"`
	Email       string `json:"Email"`
	Password    string `json:"Password"`
	PhoneNumber int    `json:"Phone_Number"`
}

type User struct {
	Name        string `json:"Name"`
	Email       string `json:"Email"`
	Password    string `json:"Password"`
	PhoneNumber int    `json:"Phone_Number"`
}
